[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "https://google.com"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rootwork"
[[social]]
  name = "gitlab"
  type = "social"
  weight = 2
  url = "https://gitlab.com/rootwork"
[[social]]
  name = "drupal"
  type = "social"
  weight = 3
  url = "https://www.drupal.org/u/rootwork"
  title = "Drupal"
[[social]]
  name = "twitter"
  weight = 4
  url = "https://twitter.com/rootwork"
[[social]]
  name = "linkedin"
  weight = 5
  url = "https://www.linkedin.com/in/ivanboothe"
[[social]]
  name = "rss"
  weight = 6
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
